# Request parameters
string execute # A task to be executed by the server
---
# Result of the movement
bool success # Finished the action sucessfuly
float64 total_duration # Time in ms for the process of executing a goal
float64 duration_goal_move # Time in ms for receiving the goal and start of the movement
float64 duration_move # Time in ms for the process of moving the arm
---
# Feedback structure
string status # GOAL_RECEIVED: Action server received the goal 
		# ARM_MOVING: Arm started the movemment
		# GOAL_CANCELED: Client canceled the movemment
		# GOAL_ENDED_SUCESS: Goal was achieved sucessfuly
		# GOAL_ABORTED: Goal was aborted because of a error or exception