# Request parameters, I used the same names as the repository for the robot parts
float64 shoulder_pan_joint  
float64 shoulder_lift_joint
float64 elbow_joint
float64 wrist_1_joint
float64 wrist_2_joint
float64 wrist_3_joint
---
# Result of the movement
bool success # Finished the action sucessfuly
float64 total_duration # Time in ms for the arm movement
---
# Feedback structure
float64 elapsed_time_goal_move # Time in ms elapsed since receiving the goal and start of the movement
float64 elapsed_time_move # Time in ms elapsed since the start and end of the movement
string status # GOAL_RECEIVED: Action server received the goal 
		# ARM_MOVING: Arm started the movemment
		# GOAL_CANCELED: Client canceled the movemment
		# GOAL_ENDED_SUCESS: Goal was achieved sucessfuly
		# GOAL_ABORTED: Goal was aborted because of a error or exception